# Generated by Django 4.2.30 on 2026-04-18 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название заявки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('unit', models.CharField(default='шт', max_length=50, verbose_name='Единица измерения')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('ordered', 'Заказ сделан'), ('completed', 'Выполнена')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поставщик')),
                ('order_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость заказа')),
                ('order_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(max_length=20, verbose_name='Статус из')),
                ('status_to', models.CharField(max_length=20, verbose_name='Статус в')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='esmsystem.request')),
            ],
            options={
                'verbose_name': 'История заявки',
                'verbose_name_plural': 'История заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
