# Generated by Django 4.2.30 on 2026-05-10 08:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esmsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.AutoField(db_column='userid', primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='role', max_length=50)),
                ('login', models.CharField(db_column='login', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password', max_length=128)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingSizeGOST',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('size_code', models.CharField(blank=True, max_length=10, null=True)),
                ('size_name', models.CharField(blank=True, max_length=50, null=True)),
                ('height_min', models.IntegerField(blank=True, null=True)),
                ('height_max', models.IntegerField(blank=True, null=True)),
                ('chest_circumference', models.IntegerField(blank=True, null=True)),
                ('waist_circumference', models.IntegerField(blank=True, null=True)),
                ('hip_circumference', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ГОСТ размер одежды',
                'verbose_name_plural': 'ГОСТ размеры одежды',
                'db_table': 'clothingsizegost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='employeeid', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='firstname', max_length=50)),
                ('second_name', models.CharField(db_column='secondname', max_length=50)),
                ('last_name', models.CharField(db_column='lastname', max_length=50)),
                ('is_active', models.BooleanField(db_column='isactive')),
                ('hire_date', models.DateField(db_column='hiredate')),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=1, null=True)),
                ('heightcm', models.IntegerField(blank=True, db_column='heightcm', null=True)),
                ('clothing_size', models.CharField(blank=True, db_column='clothingsize', max_length=10, null=True)),
                ('shoesize', models.IntegerField(blank=True, db_column='shoesize', null=True)),
                ('headsize', models.IntegerField(blank=True, db_column='headsize', null=True)),
                ('weight', models.DecimalField(blank=True, db_column='weight', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FootwearSizeGOST',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_ru', models.IntegerField(blank=True, null=True)),
                ('size_eu', models.IntegerField(blank=True, null=True)),
                ('size_us', models.IntegerField(blank=True, null=True)),
                ('foot_length_min', models.IntegerField(blank=True, null=True)),
                ('foot_length_max', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ГОСТ размер обуви',
                'verbose_name_plural': 'ГОСТ размеры обуви',
                'db_table': 'footwearsizegost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeadwearSizeGOST',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_code', models.CharField(blank=True, max_length=10, null=True)),
                ('head_circumference_min', models.IntegerField(blank=True, null=True)),
                ('head_circumference_max', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ГОСТ размер головного убора',
                'verbose_name_plural': 'ГОСТ размеры головных уборов',
                'db_table': 'headwearsizegost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IssuanceStandard',
            fields=[
                ('issuance_standard_id', models.AutoField(db_column='issuancestandardid', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
                ('period_months', models.IntegerField(db_column='period_months')),
            ],
            options={
                'verbose_name': 'Норма выдачи',
                'verbose_name_plural': 'Нормы выдачи',
                'db_table': 'issuancestandards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('nomenclature_id', models.AutoField(db_column='nomenclatureid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=200)),
                ('unit', models.CharField(db_column='unit', max_length=50)),
                ('shelf_life_months', models.IntegerField(db_column='shelflifemonths')),
                ('is_active', models.BooleanField(db_column='isactive')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатуры',
                'db_table': 'nomenclatures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(db_column='positionid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PPEIssue',
            fields=[
                ('issue_id', models.AutoField(db_column='issueid', primary_key=True, serialize=False)),
                ('issue_date', models.DateField(db_column='issuedate')),
                ('size', models.CharField(blank=True, db_column='size', max_length=20, null=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
                ('next_issue_date', models.DateField(db_column='nextissuedate')),
            ],
            options={
                'verbose_name': 'Выдача СИЗ',
                'verbose_name_plural': 'Выдачи СИЗ',
                'db_table': 'ppe_issues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('procurement_plan_id', models.AutoField(db_column='procurementplanid', primary_key=True, serialize=False)),
                ('total_quantity', models.DecimalField(db_column='totalquantity', decimal_places=2, max_digits=10)),
                ('planned_month', models.IntegerField(db_column='plannedmonth')),
                ('status', models.CharField(db_column='status', max_length=30)),
                ('created_at', models.DateTimeField(db_column='createdat', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'План закупок',
                'verbose_name_plural': 'Планы закупок',
                'db_table': 'procurementplans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestEmployee',
            fields=[
                ('request_employee_id', models.AutoField(db_column='requestemployeeid', primary_key=True, serialize=False)),
                ('height', models.IntegerField(blank=True, db_column='height', null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник в заявке',
                'verbose_name_plural': 'Сотрудники в заявках',
                'db_table': 'request_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestEmployeeItem',
            fields=[
                ('item_id', models.AutoField(db_column='itemid', primary_key=True, serialize=False)),
                ('size', models.CharField(db_column='size', max_length=20)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'СИЗ сотрудника в заявке',
                'verbose_name_plural': 'СИЗ сотрудников в заявках',
                'db_table': 'request_employee_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('item_id', models.AutoField(db_column='itemid', primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(db_column='quantityrequested', decimal_places=2, max_digits=10)),
                ('standard_title', models.CharField(db_column='standardtitle', max_length=50)),
                ('standard_unit', models.CharField(db_column='standardtnit', max_length=50)),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
                'db_table': 'requestitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(db_column='shopid', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=10)),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цеха',
                'db_table': 'shops',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'managed': False, 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='requesthistory',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'История заявки', 'verbose_name_plural': 'История заявок'},
        ),
        migrations.CreateModel(
            name='PPEIssueRecord',
            fields=[
                ('issue_id', models.AutoField(db_column='issueid', primary_key=True, serialize=False)),
                ('issue_date', models.DateField(db_column='issuedate')),
                ('size', models.CharField(blank=True, db_column='size', max_length=20, null=True)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, max_digits=10)),
                ('next_issue_date', models.DateField(db_column='nextissuedate')),
                ('comment', models.TextField(blank=True, db_column='comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('employee', models.ForeignKey(db_column='employeeid', on_delete=django.db.models.deletion.CASCADE, to='esmsystem.employee')),
                ('issued_by', models.ForeignKey(db_column='issuedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to='esmsystem.appuser')),
                ('nomenclature', models.ForeignKey(db_column='nomenclatureid', on_delete=django.db.models.deletion.CASCADE, to='esmsystem.nomenclature')),
            ],
            options={
                'verbose_name': 'Выдача СИЗ',
                'verbose_name_plural': 'Выдачи СИЗ',
                'db_table': 'ppe_issue_records',
            },
        ),
        migrations.CreateModel(
            name='PPEIssueStandard',
            fields=[
                ('standard_id', models.AutoField(db_column='standardid', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(db_column='quantity', decimal_places=2, default=1, max_digits=10)),
                ('period_months', models.IntegerField(db_column='period_months', default=12)),
                ('is_active', models.BooleanField(db_column='isactive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdat')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedat')),
                ('nomenclature', models.ForeignKey(db_column='nomenclatureid', on_delete=django.db.models.deletion.CASCADE, to='esmsystem.nomenclature')),
                ('position', models.ForeignKey(db_column='positionid', on_delete=django.db.models.deletion.CASCADE, to='esmsystem.position')),
            ],
            options={
                'verbose_name': 'Норма выдачи СИЗ',
                'verbose_name_plural': 'Нормы выдачи СИЗ',
                'db_table': 'ppe_issue_standards',
                'unique_together': {('position', 'nomenclature')},
            },
        ),
    ]
