# Generated by Django 4.2.30 on 2026-05-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esmsystem', '0002_appuser_clothingsizegost_employee_footwearsizegost_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='requests',
        ),
        migrations.AlterModelTable(
            name='requesthistory',
            table='requesthistory',
        ),
    ]
